WebUI/Areas/Admin/Controllers/SlideItemController.cs
using Core.Models;
using DataAccess.Contexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using NuGet.ContentModel;
using WebUI.Areas.Admin.ViewModels;
using WebUI.Areas.Admin.ViewModels.SiderViewModels;
using WebUI.Utilities;
using static NuGet.Packaging.PackagingConstants;

namespace WebUI.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize]
public class SlideItemController : Controller
{
    private readonly AppDbContext _context;
    private readonly IWebHostEnvironment _webHostEnvironment;
    private int _count;
    public SlideItemController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
    {
        _context = context;
        _webHostEnvironment = webHostEnvironment;
        _count = _context.SlideItems.Count();
    }

    public IActionResult Index()
    {
        ViewBag.Count = _count;
        return View(_context.SlideItems);
    }
    public async Task<IActionResult> Detail(int id)
    {
        var slideItem = await _context.SlideItems.FindAsync(id);
        if (slideItem == null) return NotFound();
        return View(slideItem);
    }

    public IActionResult Creat()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Creat(SlideItemVM slideItemVM)
    {
        if (!ModelState.IsValid) return View(slideItemVM);
        if (slideItemVM.Image == null) return NotFound();
        if (!slideItemVM.Image.CheckFileSize(300))
        {
            ModelState.AddModelError("Image", "Image size must be less than 300 kb");
            return View(slideItemVM);
        }
        if (!slideItemVM.Image.CheckFileFormat("image/"))
        {
            ModelState.AddModelError("Image", "You must choose image file type");
            return View(slideItemVM);
        }
        string? wwwroot = _webHostEnvironment.WebRootPath;
        string imageName = slideItemVM.Image.CopyFilee(wwwroot, "assets", "img", "slider");

        SlideItems slideItem = new SlideItems
        {
            Description = slideItemVM.Description,
            Tittle = slideItemVM.Tittle,
            SubTittle = slideItemVM.SubTittle,
            Image = imageName
        };
        _context.SlideItems.Add(slideItem);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        if (_count == 1)
        {
            return BadRequest();
        }
        var slideItem = await _context.SlideItems.FindAsync(id);
        if (slideItem == null) return NotFound();
        return View(slideItem);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    [ActionName("Delete")]
    public async Task<IActionResult> DeletePost(int id)
    {
        if (_count == 1)
        {
            return BadRequest();
        }
        var slideItem = await _context.SlideItems.FindAsync(id);
        if (slideItem == null) return NotFound();
        if (slideItem.Image.ToString() == null) return NotFound();

        string fileName = slideItem.Image;
        string? wwwroot = _webHostEnvironment.WebRootPath;

        try
        {
            Helper.DelteFile(wwwroot, "assets", "img", "slider", fileName);
        }
        catch (IOException ioExp)
        {
            return BadRequest(ioExp.Message);
        }

        _context.SlideItems.Remove(slideItem);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Update(int id)
    {

        var model = await _context.SlideItems.FindAsync(id);
        if (model == null) return NotFound();
        UpdateSlideItemVM updateSlideItem = new UpdateSlideItemVM
        {
            Tittle = model.Tittle,
            SubTittle = model.SubTittle,
            Description = model.Description,
            ImageName = model.Image
        };

        return View(updateSlideItem);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(int id, UpdateSlideItemVM updateSlideItem)
    {

        if (!ModelState.IsValid) return View(updateSlideItem);
        var model = await _context.SlideItems.FindAsync(id);
        if (model == null) return NotFound();
        updateSlideItem.ImageName=model.Image;

        if (updateSlideItem.Image != null)
        {

            if (!updateSlideItem.Image.CheckFileSize(300))
            {
                ModelState.AddModelError("Image", "Image size must be less than 300 kb");
                return View(updateSlideItem);
            }
            if (!updateSlideItem.Image.CheckFileFormat("image/"))
            {
                ModelState.AddModelError("Image", "You must choose image file type");
                return View(updateSlideItem);
            }
            string? wwwroot = _webHostEnvironment.WebRootPath;
            updateSlideItem.ImageName = updateSlideItem.Image.CopyFilee(wwwroot, "assets", "img", "slider");

            try
            {
                Helper.DelteFile(wwwroot, "assets", "img", "slider", model.Image);
            }
            catch (IOException ioExp)
            {
                return BadRequest(ioExp.Message);
            }
            

        }


        model.Description = updateSlideItem.Description;
        model.Tittle = updateSlideItem.Tittle;
        model.SubTittle = updateSlideItem.SubTittle;
        model.Image = updateSlideItem.ImageName;

        _context.SaveChanges();
        return RedirectToAction(nameof(Index));


    }
}

WebUI/Areas/Admin/Views/SlideItem/Creat.cshtml
@using WebUI.Areas.Admin.ViewModels
@model SlideItemVM
@{
	ViewData["Title"] = "Creat";
}

<div id="app">
	<section class="section">
		<div class="container mt-5">
			<div class="row">
				<div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
					<div class="login-brand">
						Create new slide item
					</div>

					<div class="card card-primary">
						<div class="card-header"><h3>Create</h3></div>

						<div class="card-body">
							<form method="post" enctype="multipart/form-data">
								<div class="form-group">
									<label for="Tittle">Tittle</label>
									<input asp-for="Tittle" class="form-control" >
									<span asp-validation-for="Tittle" class="text-danger"></span>
									<div class="invalid-feedback">
									</div>
								</div>

								<div class="form-group">
									<label >Subtittle</label>
									<input asp-for="SubTittle" class="form-control" >
									<span asp-validation-for="SubTittle" class="text-danger"></span>
									<div class="invalid-feedback">
									</div>
								</div>

								<div class="form-group">
									<label >Description</label>
									<input asp-for="Description" class="form-control" >
									<span asp-validation-for="Description" class="text-danger"></span>
									<div class="invalid-feedback">
									</div>
								</div>

								<div class="form-group">
									<label >Image</label>
									<input asp-for="Image" class="form-control" accept="image/*">
									<span asp-validation-for="Image" class="text-danger"></span>
									<div class="invalid-feedback">
									</div>
								</div>
								<div class="form-group">
									<button type="submit" class="btn btn-primary btn-block">
										Create
									</button>
								</div>
							</form>
						</div>
					</div>
					<div class="simple-footer">
						Copyright &copy; Mhmmd 2023
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

WebUI/Areas/Admin/Views/SlideItem/Delete.cshtml
@model SlideItems
@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-12 col-sm-6 col-lg-6">
        <div class="card">
            <div class="card-header">
                <div class="float-right">
                    <a data-collapse="#mycard-collapse" class="btn btn-icon"><i class="ion ion-minus"></i></a>
                </div>
                <h4>Show/Hide</h4>
            </div>
                <form method="post">
            <div class="collapse show" id="mycard-collapse">

                <div class="card-body">
                    <h2>
                    @Model.Tittle
                    </h2>
                </div>
                <div class="card-body">
                    <h4>
                   @Model.SubTittle
                    </h4>
                </div>
                <div class="card-body">
                   @Model.Description
                </div>
                <div class="card-body">
                    <img src="~/assets/img/slider/@Model.Image" alt="Girl in a jacket" style="width:600px;height:auto;">
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-action btn-danger"> <i class="ion-android-delete"> Delete</i></button>
                    <a asp-controller="SlideItem" asp-action="Index" class="btn btn-action btn-info"> <i class="ion-ios-list-outline">  BACK</i></a>
                </div>
            </div>
                </form>
        </div>
    </div>
</div>

WebUI/Areas/Admin/Views/SlideItem/Detail.cshtml
@model SlideItems
@{
    ViewData["Title"] = "Detail";
}

<div class="row">
    <div class="col-12 col-sm-6 col-lg-6">
        <div class="card">
            <div class="card-header">
                <div class="float-right">
                    <a data-collapse="#mycard-collapse" class="btn btn-icon"><i class="ion ion-minus"></i></a>
                </div>
                <h4>Show/Hide</h4>
            </div>
            <div class="collapse show" id="mycard-collapse">
                <div class="card-body">
                    <h2>
                        @Model.Tittle
                    </h2>
                </div>
                <div class="card-body">
                    <h4>
                        @Model.SubTittle
                    </h4>
                </div>
                <div class="card-body">
                    @Model.Description
                </div>
                <div class="card-body">
                    <img src="~/assets/img/slider/@Model.Image" alt="Girl in a jacket" style="width:600px;height:auto;">
                </div>
                <div class="card-footer">
                    <a asp-controller="SlideItem" asp-action="Index" class="btn btn-action btn-info"> <i class="ion-ios-list-outline">  BACK</i></a>
                </div>
            </div>
        </div>
    </div>
</div>

WebUI/Areas/Admin/Views/SlideItem/Index.cshtml
@model IEnumerable<SlideItems>

@{
	ViewData["Title"] = "Index";
}

<section class="section">
	<div class="section-body">
		<div class="row mt-5">
			<div class="col-12 col-md-6 col-lg-6">
				<div class="card">
					<div class="card-header">
						<h4>Slide Items</h4>
					</div>
					<div class="card-body">
					<div>
						<a asp-controller="SlideItem" asp-action="Creat"  type="button" class="btn btn-action btn-secondary"> <i class="ion-ios-upload-outline"></i> Creat</a>
					</div>
						<div class="table-responsive">
							<table class="table table-bordered">
								<tr>
									<th>Image</th>
									<th>Tittle</th>
									<th>Subtittle</th>
									<th>Actions</th>
								</tr>
								@foreach (var item in Model)
								{
								<tr>
									<td><img src="~/assets/img/slider/@item.Image" alt="Girl in a jacket" style="width:200px;height:auto;"></td>
									<td>@item.Tittle</td>
									<td>@item.SubTittle</td>
									<td>
										<a   asp-controller="SlideItem"  asp-action="Detail" asp-route-id="@item.Id" class="btn btn-action btn-warning"> <i class="ion ion-ios-information-outline"></i> Detail</a>
										<a asp-controller="SlideItem" asp-action="Update" asp-route-id="@item.Id" class="btn btn-action btn-primary"> <i class="ion-android-create"></i>  Update</a>
										<a	 asp-controller="SlideItem" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-action btn-danger @(ViewBag.Count==1?"disabled":"")"> <i class="ion-android-delete"></i> Delete</a>
									</td>
								</tr>
								}

							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

WebUI/Areas/Admin/Views/SlideItem/Update.cshtml
@using WebUI.Areas.Admin.ViewModels.SiderViewModels
@model UpdateSlideItemVM
@{
	ViewData["Title"] = "Creat";
}

<div id="app">
	<section class="section">
		<div class="container mt-5">
			<div class="row">
				<div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
					<div class="login-brand">
						Update slide item
					</div>

					<div class="card card-primary">
						<div class="card-header"><h3>Update</h3></div>

						<div class="card-body">
							<form method="post" enctype="multipart/form-data">
								
								<div class="card-body">
									<img src="~/assets/img/slider/@Model.ImageName" alt="Girl in a jacket" style="width:200px;height:auto;">
								</div>

								<div class="form-group">
									<label >Image</label>
									<input asp-for="Image" class="form-control" accept="image/*">
									<div class="invalid-feedback">
									</div>
								</div>
								<div class="form-group">
									<label for="Tittle">Tittle</label>
									<input asp-for="Tittle" class="form-control" >
									<span asp-validation-for="Tittle" class="text-danger"></span>
									<div class="invalid-feedback">
									</div>
								</div>

								<div class="form-group">
									<label >Subtittle</label>
									<input asp-for="SubTittle" class="form-control" >
									<span asp-validation-for="SubTittle" class="text-danger"></span>
									<div class="invalid-feedback">
									</div>
								</div>

								<div class="form-group">
									<label >Description</label>
									<input asp-for="Description" class="form-control" >
									<span asp-validation-for="Description" class="text-danger"></span>
									<div class="invalid-feedback">
									</div>
								</div>

								<div class="form-group">
									<button type="submit" class="btn btn-primary btn-block">
										Update
									</button>
								</div>
							</form>
						</div>
					</div>
					<div class="simple-footer">
						Copyright &copy; Mhmmd 2023
					</div>
				</div>
			</div>
		</div>
	</section>
</div>